-- Seed file: 001-qatar-zones.sql
-- All 98 Qatar zones with English/Arabic names and municipality data
-- Uses ON CONFLICT to safely re-run without duplicates

INSERT INTO zones (zone_number, zone_name, zone_name_ar, municipality, municipality_ar) VALUES
(1, 'Doha Port', 'ميناء الدوحة', 'Ad-Dawhah', 'الدوحة'),
(2, 'Al Jasra', 'الجسرة', 'Ad-Dawhah', 'الدوحة'),
(3, 'Al Bidda', 'البدع', 'Ad-Dawhah', 'الدوحة'),
(4, 'Al Hitmi', 'الحتمي', 'Ad-Dawhah', 'الدوحة'),
(5, 'Najma', 'نجمة', 'Ad-Dawhah', 'الدوحة'),
(6, 'Old Al Ghanim', 'الغانم القديم', 'Ad-Dawhah', 'الدوحة'),
(7, 'Musheireb', 'مشيرب', 'Ad-Dawhah', 'الدوحة'),
(8, 'Al Asmakh', 'الأصمخ', 'Ad-Dawhah', 'الدوحة'),
(9, 'Al Salata', 'السلطة', 'Ad-Dawhah', 'الدوحة'),
(10, 'Al Mirqab', 'المرقاب', 'Ad-Dawhah', 'الدوحة'),
(11, 'Musheireb Al Jadeed', 'مشيرب الجديد', 'Ad-Dawhah', 'الدوحة'),
(12, 'Doha Al Jadeed', 'الدوحة الجديدة', 'Ad-Dawhah', 'الدوحة'),
(13, 'Bin Mahmoud North', 'بن محمود الشمالية', 'Ad-Dawhah', 'الدوحة'),
(14, 'Bin Mahmoud South', 'بن محمود الجنوبية', 'Ad-Dawhah', 'الدوحة'),
(15, 'Rawdat Al Khail', 'روضة الخيل', 'Ad-Dawhah', 'الدوحة'),
(16, 'Al Mansoura', 'المنصورة', 'Ad-Dawhah', 'الدوحة'),
(17, 'Fereej Bin Omran', 'فريج بن عمران', 'Ad-Dawhah', 'الدوحة'),
(18, 'Al Muntazah', 'المنتزه', 'Ad-Dawhah', 'الدوحة'),
(19, 'Old Airport', 'المطار القديم', 'Ad-Dawhah', 'الدوحة'),
(20, 'Al Maamoura', 'المعمورة', 'Ad-Dawhah', 'الدوحة'),
(21, 'Al Hilal', 'الهلال', 'Ad-Dawhah', 'الدوحة'),
(22, 'Al Sadd', 'السد', 'Ad-Dawhah', 'الدوحة'),
(23, 'Al Mirqab Al Jadeed', 'المرقاب الجديد', 'Ad-Dawhah', 'الدوحة'),
(24, 'Al Nasr', 'النصر', 'Ad-Dawhah', 'الدوحة'),
(25, 'Dafna', 'الدفنة', 'Ad-Dawhah', 'الدوحة'),
(26, 'Al Qassar', 'القصار', 'Ad-Dawhah', 'الدوحة'),
(27, 'Leabaib', 'لعبيب', 'Ad-Dawhah', 'الدوحة'),
(28, 'The Pearl', 'اللؤلؤة', 'Ad-Dawhah', 'الدوحة'),
(29, 'Ras Abu Aboud', 'رأس أبو عبود', 'Ad-Dawhah', 'الدوحة'),
(30, 'Al Khulaifat', 'الخليفات', 'Ad-Dawhah', 'الدوحة'),
(31, 'Madinat Khalifa North', 'مدينة خليفة الشمالية', 'Ad-Dawhah', 'الدوحة'),
(32, 'Al Thumama', 'الثمامة', 'Ad-Dawhah', 'الدوحة'),
(33, 'Madinat Khalifa South', 'مدينة خليفة الجنوبية', 'Ad-Dawhah', 'الدوحة'),
(34, 'Al Gharrafa', 'الغرافة', 'Ad-Dawhah', 'الدوحة'),
(35, 'Al Duhail North', 'الدحيل الشمالي', 'Ad-Dawhah', 'الدوحة'),
(36, 'Al Duhail South', 'الدحيل الجنوبي', 'Ad-Dawhah', 'الدوحة'),
(37, 'Al Markhiya', 'المرخية', 'Ad-Dawhah', 'الدوحة'),
(38, 'Al Tarfa', 'الطرفة', 'Ad-Dawhah', 'الدوحة'),
(39, 'Al Luqta', 'اللقطة', 'Ad-Dawhah', 'الدوحة'),
(40, 'Al Waab', 'الوعب', 'Ad-Dawhah', 'الدوحة'),
(41, 'Al Aziziya', 'العزيزية', 'Ad-Dawhah', 'الدوحة'),
(42, 'Fereej Al Ali', 'فريج العلي', 'Ad-Dawhah', 'الدوحة'),
(43, 'Umm Ghuwailina', 'أم غويلينة', 'Ad-Dawhah', 'الدوحة'),
(44, 'Al Messila', 'المسيلة', 'Ad-Dawhah', 'الدوحة'),
(45, 'West Bay', 'الخليج الغربي', 'Ad-Dawhah', 'الدوحة'),
(46, 'West Bay Lagoon', 'لاجون الخليج الغربي', 'Ad-Dawhah', 'الدوحة'),
(47, 'Fereej Abdul Aziz', 'فريج عبدالعزيز', 'Ad-Dawhah', 'الدوحة'),
(48, 'Al Rumaila', 'الرميلة', 'Ad-Dawhah', 'الدوحة'),
(49, 'Wadi Al Sail', 'وادي السيل', 'Ad-Dawhah', 'الدوحة'),
(50, 'Onaiza', 'عنيزة', 'Ad-Dawhah', 'الدوحة'),
(51, 'New Al Rayyan', 'الريان الجديد', 'Al Rayyan', 'الريان'),
(52, 'Al Rayyan Al Qadeem', 'الريان القديم', 'Al Rayyan', 'الريان'),
(53, 'Muaither North', 'معيذر الشمالي', 'Al Rayyan', 'الريان'),
(54, 'Muaither South', 'معيذر الجنوبي', 'Al Rayyan', 'الريان'),
(55, 'Ain Khaled', 'عين خالد', 'Al Rayyan', 'الريان'),
(56, 'Al Shagub', 'الشقب', 'Al Rayyan', 'الريان'),
(57, 'Nuaija', 'نعيجة', 'Ad-Dawhah', 'الدوحة'),
(58, 'Al Muraikh', 'المريخ', 'Ad-Dawhah', 'الدوحة'),
(59, 'Hazm Al Markhiya', 'حزم المرخية', 'Ad-Dawhah', 'الدوحة'),
(60, 'Fereej Al Nasr', 'فريج النصر', 'Ad-Dawhah', 'الدوحة'),
(61, 'Fereej Al Amir', 'فريج الأمير', 'Ad-Dawhah', 'الدوحة'),
(62, 'Umm Lekhba', 'أم لخبة', 'Ad-Dawhah', 'الدوحة'),
(63, 'Al Kheesa', 'الخيسة', 'Ad-Dawhah', 'الدوحة'),
(64, 'Umm Salal Mohammed', 'أم صلال محمد', 'Umm Salal', 'أم صلال'),
(65, 'Umm Salal Ali', 'أم صلال علي', 'Ad-Dawhah', 'الدوحة'),
(66, 'Al Ebb', 'العب', 'Ad-Dawhah', 'الدوحة'),
(67, 'Semaisma', 'سميسمة', 'Ad-Dawhah', 'الدوحة'),
(68, 'Lusail', 'لوسيل', 'Ad-Dawhah', 'الدوحة'),
(69, 'Al Daayen', 'الضعاين', 'Al Daayen', 'الضعاين'),
(70, 'Umm Qarn', 'أم قرن', 'Al Daayen', 'الضعاين'),
(71, 'Umm Salal', 'أم صلال', 'Umm Salal', 'أم صلال'),
(72, 'Al Shahaniya', 'الشحانية', 'Al-Shahaniya', 'الشحانية'),
(73, 'Dukhan', 'دخان', 'Al-Shahaniya', 'الشحانية'),
(74, 'Al Khor', 'الخور', 'Al Khor', 'الخور'),
(75, 'Al Thakhira', 'الذخيرة', 'Al Khor', 'الخور'),
(76, 'Ras Laffan', 'رأس لفان', 'Al Khor', 'الخور'),
(77, 'Madinat Al Shamal', 'مدينة الشمال', 'Al Shamal', 'الشمال'),
(78, 'Al Ruwais', 'الرويس', 'Al Shamal', 'الشمال'),
(79, 'Al Ghuwairiya', 'الغويرية', 'Al Shamal', 'الشمال'),
(80, 'Rawdat Rashid', 'روضة راشد', 'Al-Shahaniya', 'الشحانية'),
(81, 'Al Sailiya', 'السيلية', 'Al Rayyan', 'الريان'),
(82, 'Al Jumailiya', 'الجميلية', 'Al-Shahaniya', 'الشحانية'),
(83, 'Abu Hamour', 'أبو هامور', 'Al Rayyan', 'الريان'),
(84, 'Al Nasraniya', 'النصرانية', 'Al-Shahaniya', 'الشحانية'),
(85, 'Al Themaid', 'الثميد', 'Al-Shahaniya', 'الشحانية'),
(86, 'Rawdat Al Hamama', 'روضة الحمامة', 'Al-Shahaniya', 'الشحانية'),
(87, 'Jeryan Nejaima', 'جريان نجيمة', 'Ad-Dawhah', 'الدوحة'),
(88, 'Mehairja', 'محيرجة', 'Ad-Dawhah', 'الدوحة'),
(89, 'Al Egla', 'العقلة', 'Ad-Dawhah', 'الدوحة'),
(90, 'Al Wakrah', 'الوكرة', 'Al Wakrah', 'الوكرة'),
(91, 'Al Wukair', 'الوكير', 'Al Wakrah', 'الوكرة'),
(92, 'Mesaieed', 'مسيعيد', 'Al Wakrah', 'الوكرة'),
(93, 'Al Kiranah', 'الكرعانة', 'Al Wakrah', 'الوكرة'),
(94, 'Abu Nakhla', 'أبو نخلة', 'Al Wakrah', 'الوكرة'),
(95, 'Muaither', 'معيذر', 'Al Wakrah', 'الوكرة'),
(96, 'Barwa City', 'مدينة بروة', 'Al Rayyan', 'الريان'),
(97, 'Education City', 'المدينة التعليمية', 'Al Rayyan', 'الريان'),
(98, 'Lusail City', 'مدينة لوسيل', 'Ad-Dawhah', 'الدوحة')
ON CONFLICT (zone_number) DO NOTHING;
